In [4]:
import numpy as np
import PIL
import matplotlib.pyplot as plt
import pandas as pd
import os
import copy
import scipy.io
import sys
sys.path.append('/user_data/mmhender/texture_synthesis/code/')
import things_utils

import warnings
warnings.filterwarnings('ignore')

In [5]:
things_root = '/user_data/mmhender/things/'

In [6]:
project_root = '/user_data/mmhender/featsynth/'

In [17]:
# make_trial_info(234355)
make_trial_info(565676)

['office_supply' 'body_part' 'fruit' 'bird' 'part_of_car' 'toy' 'dessert'
 'drink' 'clothing' 'vegetable']
saving to /user_data/mmhender/featsynth/expt_design/trial_info_565676.csv

In [74]:
# ti = pd.read_csv('/user_data/mmhender/texture_synthesis/expt_design/trial_info_456466.csv')
ti = pd.read_csv('/user_data/mmhender/featsynth/expt_design/trial_info_565676.csv')
ti

,trial_num,categ_ind,concept_ind,super_name,basic_name,ex_num,image_type_num,image_name,target_present,cue_level,cue_name,run_number
0,709.0,5.0,5.0,toy,dollhouse,1.0,4.0,dollhouse_02s/grid5_1x1_upto_pool4.png,False,basic,hula_hoop,1
1,978.0,8.0,0.0,clothing,cape,3.0,3.0,cape_04s/grid5_1x1_upto_pool3.png,False,super,dessert,1
2,779.0,6.0,2.0,dessert,baklava,3.0,4.0,baklava_04s/grid5_1x1_upto_pool4.png,False,super,body_part,1
3,1059.0,8.0,4.0,clothing,pantsuit,3.0,4.0,pantsuit_04s/grid5_1x1_upto_pool4.png,False,super,fruit,1
4,1133.0,9.0,2.0,vegetable,arugula,2.0,3.0,arugula_03s/grid5_1x1_upto_pool3.png,True,super,vegetable,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,971.0,8.0,0.0,clothing,cape,2.0,1.0,cape_03s/grid5_1x1_upto_pool1.png,True,super,clothing,12
1196,160.0,1.0,2.0,body_part,elbow,0.0,0.0,elbow_01b/orig.png,True,basic,elbow,12
1197,949.0,7.0,5.0,drink,juice,1.0,4.0,juice_02s/grid5_1x1_upto_pool4.png,False,basic,smoothie,12
1198,472.0,3.0,5.0,bird,toucan,2.0,2.0,toucan_03s/grid5_1x1_upto_pool2.png,True,super,bird,12
1199,672.0,5.0,3.0,toy,puppet,2.0,2.0,puppet_03s/grid5_1x1_upto_pool2.png,True,super,toy,12

In [8]:
import json

In [22]:
json_filename = '/user_data/mmhender/featsynth/expt_design/trial_info_565676.json'
ti.iloc[0:10].to_json(json_filename, orient='index')

In [26]:
ti_edited = ti.iloc[0:4]
ti_edited['t'] = np.arange(1,5)
ti_edited['imgname'] = ['orig.png' for ii in range(4)]
ti_edited['text'] = np.repeat(['A', 'B'], 2)
ti_edited['correct_response'] = np.repeat([1,2], 2)
# { t: 1, imgname: im1, text: 'A', correct_response: '1'}
ti_edited

,trial_num,categ_ind,concept_ind,super_name,basic_name,ex_num,image_type_num,image_name,target_present,cue_level,cue_name,run_number,t,imgname,text,correct_response
0,709.0,5.0,5.0,toy,dollhouse,1.0,4.0,dollhouse_02s/grid5_1x1_upto_pool4.png,False,basic,hula_hoop,1,1,orig.png,A,1
1,978.0,8.0,0.0,clothing,cape,3.0,3.0,cape_04s/grid5_1x1_upto_pool3.png,False,super,dessert,1,2,orig.png,A,1
2,779.0,6.0,2.0,dessert,baklava,3.0,4.0,baklava_04s/grid5_1x1_upto_pool4.png,False,super,body_part,1,3,orig.png,B,2
3,1059.0,8.0,4.0,clothing,pantsuit,3.0,4.0,pantsuit_04s/grid5_1x1_upto_pool4.png,False,super,fruit,1,4,orig.png,B,2

In [33]:
test = pd.DataFrame()
test['t'] = np.arange(1,5)
test['imgname'] = ['orig.png' for ii in range(4)]
test['text'] = np.repeat(['A', 'B'], 2)
test['correct_response'] = np.repeat([1,2], 2)
json_filename = '/user_data/mmhender/featsynth/expt_design/trials_test_short.json'
test.to_json(json_filename, orient='records')

In [29]:
# ti_edited.to_json(json_filename, orient='index')
# ti_edited.to_json(json_filename, orient='split')
ti_edited.to_json(json_filename, orient='records')

In [18]:
pd.read_json('/user_data/mmhender/featsynth/expt_design/trial_info_565676.json', orient='split')

,trial_num,categ_ind,concept_ind,super_name,basic_name,ex_num,image_type_num,image_name,target_present,cue_level,cue_name,run_number
0,709,5,5,toy,dollhouse,1,4,dollhouse_02s/grid5_1x1_upto_pool4.png,False,basic,hula_hoop,1
1,978,8,0,clothing,cape,3,3,cape_04s/grid5_1x1_upto_pool3.png,False,super,dessert,1
2,779,6,2,dessert,baklava,3,4,baklava_04s/grid5_1x1_upto_pool4.png,False,super,body_part,1
3,1059,8,4,clothing,pantsuit,3,4,pantsuit_04s/grid5_1x1_upto_pool4.png,False,super,fruit,1
4,1133,9,2,vegetable,arugula,2,3,arugula_03s/grid5_1x1_upto_pool3.png,True,super,vegetable,1
5,764,6,2,dessert,baklava,0,4,baklava_01s/grid5_1x1_upto_pool4.png,True,basic,baklava,1
6,453,3,4,bird,peacock,2,3,peacock_03s/grid5_1x1_upto_pool3.png,True,super,bird,1
7,541,4,3,part_of_car,headrest,0,1,headrest_01b/grid5_1x1_upto_pool1.png,True,basic,headrest,1
8,920,7,4,drink,tea,0,0,tea_01b/orig.png,True,basic,tea,1
9,922,7,4,drink,tea,0,2,tea_01b/grid5_1x1_upto_pool2.png,True,basic,tea,1

In [40]:
str(dict(ti.iloc[0]))

"{'trial_num': 709.0, 'categ_ind': 5.0, 'concept_ind': 5.0, 'super_name': 'toy', 'basic_name': 'dollhouse', 'ex_num': 1.0, 'image_type_num': 4.0, 'image_name': 'dollhouse_02s/grid5_1x1_upto_pool4.png', 'target_present': False, 'cue_level': 'basic', 'cue_name': 'hula_hoop', 'run_number': 1}"

In [47]:
ti_edited = ti.iloc[0:4]
ti_edited['t'] = np.arange(1,5)
ti_edited['imgname'] = ['orig.png' for ii in range(4)]
ti_edited['text'] = np.repeat(['A', 'B'], 2)
ti_edited['correct_response'] = np.repeat([1,2], 2)

In [55]:
bool_dict = dict({False: 'false',True:'true'})

In [53]:
str(ti_edited.iloc[0]['target_present'])

'False'

In [73]:
jsfilename = '/user_data/mmhender/featsynth/expt_design/trialseq_test.js'

with open(jsfilename,'w') as f:
    
    # line='import gorilla = require("gorilla/gorilla");'
    # f.write(line)

    # f.write('\n\n[\n')

    f.write('var info = [\n')
    
    for tt in range(4):
        trial_info = dict(ti_edited.iloc[tt])
        
        trial_info['imgname'] = trial_info['image_name'].split('/')[1]
        # trial_info['imgname'] = 'gorilla.stimuliURL(\'%s\')'%trial_info['image_name'].split('/')[1]
        trial_info['text'] = trial_info['super_name']
        trial_info['target_present'] = bool_dict[trial_info['target_present']]
        
        f.write('    {\n')
        # f.write(str(trial_info))
        for key,val in zip(trial_info.keys(), trial_info.values()):
            
            if isinstance(val, str):
                f.write('    \'%s\': \'%s\',\n'%(key, val))
            else:
                f.write('    \'%s\': %d,\n'%(key, val))
        
        f.write('    },\n')
        
        # f.write(',\n')

    f.write('];\n')

In [68]:
isinstance(trial_info['categ_ind'], str)

False

In [76]:
def make_trial_json(df, json_filename, var_name='info'):
    
    n_trials = df.shape[0]

    with open(jsfilename,'w') as f:

        f.write('var %s = [\n'%var_name)

        for tt in range(n_trials):
            
            trial_info = dict(df.iloc[tt])

            f.write('    {\n')
            for key,val in zip(trial_info.keys(), trial_info.values()):

                if isinstance(val, str):
                    f.write('    \'%s\': \'%s\',\n'%(key, val))
                else:
                    f.write('    \'%s\': %d,\n'%(key, val))

            f.write('    },\n')

        f.write('];\n')