In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cm
import itertools

import os, sys

project_root = '/user_data/mmhender/featsynth/'
# sys.path.append(os.path.join(project_root, 'code'))
sys.path.insert(0, os.path.join(project_root, 'code'))
from utils import stats_utils, plot_utils
from behav_analysis import analyze_expt3

In [24]:
fn = '/user_data/mmhender/featsynth/features/raw/images_things64_list.csv'
df = pd.read_csv(fn)
np.array(df['basic_name'][0::12])

array(['beetle', 'bee', 'butterfly', 'grasshopper', 'caterpillar', 'ant',
       'moth', 'mosquito', 'dog', 'lion', 'horse', 'squirrel', 'elephant',
       'cow', 'pig', 'rabbit', 'pea', 'corn', 'pumpkin', 'onion',
       'cabbage', 'lettuce', 'beet', 'asparagus', 'grape', 'cherry',
       'raspberry', 'apple', 'pear', 'banana', 'pomegranate', 'coconut',
       'pencil', 'knife', 'axe', 'broom', 'hammer', 'shovel', 'spoon',
       'scissors', 'bell', 'guitar', 'piano', 'drum', 'violin', 'trumpet',
       'clarinet', 'cymbal', 'table', 'bench', 'couch', 'television',
       'bed', 'chair', 'refrigerator', 'lamp', 'ship', 'train',
       'airplane', 'truck', 'car', 'bus', 'motorcycle', 'canoe'],
      dtype=object)

In [2]:
trial_data_all, subjects, cue_level_names, image_type_names = analyze_expt3.load_data()
 
n_subjects = len(subjects)
n_cue_levels = len(cue_level_names)
n_image_types = len(image_type_names)

In [3]:
super_names, super_cbinds, basic_names, basic_inds, \
        super_names_long, super_inds_long, n_basic, n_super, n_basic_each_super = \
            analyze_expt3.get_categ_info()

In [19]:
bi =0;

td = trial_data_all[trial_data_all['basic_name']==basic_names[bi]]

td

,Unnamed: 0,trial_num_overall,run_number,trial_in_run,image_set_num,random_order_number,categ_ind,concept_ind,super_name,basic_name,...,right_name,correct_resp,rt,resp,correct,which_cb,pixels_per_degree,subject,gorilla_pub_id,worker_id
84,84,84,3,4,0.0,6,0.0,0.0,insect,beetle,...,insect,2,501.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
108,108,108,3,28,0.0,6,0.0,0.0,insect,beetle,...,insect,2,800.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
121,121,121,4,1,0.0,6,0.0,0.0,insect,beetle,...,beetle,2,1184.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
122,122,122,4,2,0.0,6,0.0,0.0,insect,beetle,...,grasshopper,1,1173.0,2,False,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
137,137,137,4,17,0.0,6,0.0,0.0,insect,beetle,...,moth,1,NaN,-1,False,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10958,78,78,2,38,0.0,14,0.0,0.0,insect,beetle,...,beetle,2,599.0,1,False,1,48.731987,18,62db2644ab0a3a353c0dcb54,62db2644ab0a3a353c0dcb54
10996,116,116,3,36,0.0,14,0.0,0.0,insect,beetle,...,furniture,1,505.0,1,True,1,48.731987,18,62db2644ab0a3a353c0dcb54,62db2644ab0a3a353c0dcb54
11235,355,355,9,35,0.0,14,0.0,0.0,insect,beetle,...,insect,2,722.0,1,False,1,48.731987,18,62db2644ab0a3a353c0dcb54,62db2644ab0a3a353c0dcb54
11287,407,407,11,7,0.0,14,0.0,0.0,insect,beetle,...,insect,2,879.0,2,True,1,48.731987,18,62db2644ab0a3a353c0dcb54,62db2644ab0a3a353c0dcb54
11366,486,486,13,6,0.0,14,0.0,0.0,insect,beetle,...,vehicle,1,792.0,1,True,1,48.731987,18,62db2644ab0a3a353c0dcb54,62db2644ab0a3a353c0dcb54

In [20]:
180/10

18.0

In [4]:
trial_data_all.shape

(11520, 30)

In [14]:
trial_data_all.keys()

Index(['Unnamed: 0', 'trial_num_overall', 'run_number', 'trial_in_run',
       'image_set_num', 'random_order_number', 'categ_ind', 'concept_ind',
       'super_name', 'basic_name', 'ex_num', 'image_type_num', 'image_type',
       'image_name', 'dropbox_url', 'cue_level_num', 'cue_level', 'cue_name',
       'distractor_name', 'left_name', 'right_name', 'correct_resp', 'rt',
       'resp', 'correct', 'which_cb', 'pixels_per_degree', 'subject',
       'gorilla_pub_id', 'worker_id'],
      dtype='object')

In [9]:
td = trial_data_all[trial_data_all['subject']==1]

In [13]:
bi = 0;
td[td['basic_name']==basic_names[bi]]

,Unnamed: 0,trial_num_overall,run_number,trial_in_run,image_set_num,random_order_number,categ_ind,concept_ind,super_name,basic_name,...,right_name,correct_resp,rt,resp,correct,which_cb,pixels_per_degree,subject,gorilla_pub_id,worker_id
84,84,84,3,4,0.0,6,0.0,0.0,insect,beetle,...,insect,2,501.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
108,108,108,3,28,0.0,6,0.0,0.0,insect,beetle,...,insect,2,800.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
121,121,121,4,1,0.0,6,0.0,0.0,insect,beetle,...,beetle,2,1184.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
122,122,122,4,2,0.0,6,0.0,0.0,insect,beetle,...,grasshopper,1,1173.0,2,False,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
137,137,137,4,17,0.0,6,0.0,0.0,insect,beetle,...,moth,1,NaN,-1,False,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
142,142,142,4,22,0.0,6,0.0,0.0,insect,beetle,...,bee,1,NaN,-1,False,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
145,145,145,4,25,0.0,6,0.0,0.0,insect,beetle,...,bee,1,560.0,1,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
161,161,161,5,1,0.0,6,0.0,0.0,insect,beetle,...,dessert,1,NaN,-1,False,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
276,276,276,7,36,0.0,6,0.0,0.0,insect,beetle,...,dessert,1,696.0,1,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
485,485,485,13,5,0.0,6,0.0,0.0,insect,beetle,...,tool,1,647.0,2,False,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1

In [15]:
si = 0;
td[td['super_name']==super_names[si]]

,Unnamed: 0,trial_num_overall,run_number,trial_in_run,image_set_num,random_order_number,categ_ind,concept_ind,super_name,basic_name,...,right_name,correct_resp,rt,resp,correct,which_cb,pixels_per_degree,subject,gorilla_pub_id,worker_id
12,12,12,1,12,0.0,6,0.0,7.0,insect,mosquito,...,vegetable,1,599.0,1,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
33,33,33,1,33,0.0,6,0.0,4.0,insect,caterpillar,...,insect,2,910.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
34,34,34,1,34,0.0,6,0.0,6.0,insect,moth,...,fruit,1,633.0,1,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
35,35,35,1,35,0.0,6,0.0,3.0,insect,grasshopper,...,musical_instrument,1,976.0,1,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
84,84,84,3,4,0.0,6,0.0,0.0,insect,beetle,...,insect,2,501.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,577,577,15,17,0.0,6,0.0,6.0,insect,moth,...,insect,2,797.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
588,588,588,15,28,0.0,6,0.0,5.0,insect,ant,...,vegetable,1,912.0,1,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
589,589,589,15,29,0.0,6,0.0,1.0,insect,bee,...,insect,2,627.0,2,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
592,592,592,15,32,0.0,6,0.0,4.0,insect,caterpillar,...,dessert,1,1120.0,1,True,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1
595,595,595,15,35,0.0,6,0.0,6.0,insect,moth,...,insect,2,1598.0,1,False,1,31.259692,1,5f075b60ae5a1d3504e8ccb1,5f075b60ae5a1d3504e8ccb1

In [16]:
80/2/5

8.0

In [5]:
subjects

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])